### ISSUE TITLE
header callback gets called 2 times (JRUBY)

### ISSUE THREAD

**Issue by HoneyryderChuck** [tmm1/http_parser.rb#52]
I've found a bug in the parser while testing some implementation here, and discovered that there's something wrong with the java parser, specifically: header callback is being called 2 times, and the last one after the #on_body calls, before the parsing is done. I've devised this test script to demonstrate: 

```ruby
require "http_parser"

$payload = "POST / HTTP/1.1\r\nAccept-Encoding: identity;q=1.0\r\nAccept: */*\r\nUser-Agent: Ruby\r\nHost: 127.0.0.1:58229\r\nTransfer-Encoding: chunked\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\nb\r\nonetwothree\r\n0\r\n\r\n".b


$parser = HTTP::Parser.new

$parser.on_message_begin = -> { puts "started!!!" }
$parser.on_headers_complete = -> (h) { puts "headers! #{h}" }
$parser.on_body = -> (ch) { puts "chunk! #{ch}" }
$parser.on_message_complete = -> { puts "we're done!!" }

$parser << $payload

# running with jruby-9.1.13.0
# started!!!
# headers! {"Accept-Encoding"=>"identity;q=1.0", "Accept"=>"*/*", "User-Agent"=>"Ruby", "Host"=>"127.0.0.1:58229", "Transfer-Encoding"=>"chunked", "Content-Type"=>"application/x-www-form-urlencoded"}
# chunk! onetwothree
# headers! {"Accept-Encoding"=>"identity;q=1.0", "Accept"=>"*/*", "User-Agent"=>"Ruby", "Host"=>"127.0.0.1:58229", "Transfer-Encoding"=>"chunked", "Content-Type"=>"application/x-www-form-urlencoded"}
# we're done!!
```

The CRuby implementation works as expected. I've also noticed that 2 tests are failing for jruby. Maybe that could be the issue(?).

**Comment by a2800276** [comment]
Hi HoneyryderChuck,

thanks very much for the PR. 

1.) As stated in the README, I'm currently no longer maintaining this project, it was transfered to the ruby http parser folks, as they were the primary (only?) users. (https://github.com/http-parser/http-parser.java) not sure if this is being maintained.

2.) In case you can't find anyone there to merge your fix, with the tiny provision that it would require a small test that demonstrates the problem and illustrates that your patch fixes it.

Sorry about that & thanks again!
    -tim
