### ISSUE TITLE
MacOS: Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by zarapustra** [tmm1/http_parser.rb#60]
**ruby** 2.5.2p104 (2018-10-18 revision 65133) [x86_64-darwin17]
gem '**rails**', '~> 5.2.1'
**macos** 10.14.1
**Homebrew** 1.8.4
gem 'twitter', github: 'sferik/twitter', require: false

    Fetching http_parser.rb 0.6.0
    Installing http_parser.rb 0.6.0 with native extensions
    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    
        current directory: /Users/svezhatinka/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
    /Users/svezhatinka/.rbenv/versions/2.5.2/bin/ruby -r ./siteconf20181129-13283-1wwtham.rb extconf.rb
    creating Makefile
    
    current directory: /Users/svezhatinka/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
    make "DESTDIR=" clean
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at:
    /Library/Developer/CommandLineTools/usr/bin/xcrun
    
    current directory: /Users/svezhatinka/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
    make "DESTDIR="
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at:
    /Library/Developer/CommandLineTools/usr/bin/xcrun
    
    make failed, exit code 1
    
    Gem files will remain installed in /Users/svezhatinka/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0 for inspection.
    Results logged to
    /Users/svezhatinka/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0-static/http_parser.rb-0.6.0/gem_make.out
    
    An error occurred while installing http_parser.rb (0.6.0), and Bundler cannot continue.
    Make sure that `gem install http_parser.rb -v '0.6.0' --source 'https://rubygems.org/'` succeeds before bundling.
    
    In Gemfile:
      twitter was resolved to 6.2.0, which depends on
        http was resolved to 3.3.0, which depends on
          http_parser.rb

**Comment by zarapustra** [comment]
`xcode-select --install` helped

**Comment by robbevp** [comment]
For people with similar errors:
I had the same `Failed to build gem native extension.` error, but caused by spaces in the folder name. Putting the project in a folderpath without any spaces solved this.

**Comment by ashie** [comment]
I've succeeded build v0.6.1 on macOS 11.4 with a path which includes spaces.
