### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by MSP-Greg** [tmm1/http_parser.rb#61]
Noticed something odd when trying to install the gem on Windows.  Many windows users have a space in their username, and I normally run that way.  I have not found any issues with it.

When I install the gem, I get an error during compile:
```
compiling ruby_http_parser.c
x86_64-w64-mingw32-gcc.exe: error: T/.gem/ruby/2.7.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser: No such file or directory
```

Which is the user gem folder split where the space exists.  But, I don't have the problem when installing EventMachine.  I assume it's something in `extconf.rb`, but I'm not much of a c type...

If you have any interest in testing on Appveyor or building the gem there (or both), I'd be happy to help.  Landed here wrestling with Jekyll...

**Comment by tmm1** [comment]
Is anyone interested in taking over maintenance of this project?

**Comment by ashie** [comment]
I've succeeded build v0.6.1 on Windows 10 with a path which includes spaces.
I used RubyInstaller 2.7.2-1.
