### ISSUE TITLE
Release version 0.6.1 please

### ISSUE THREAD

**Issue by shyamrox** [tmm1/http_parser.rb#65]
Hello,
    It looks like http_parser.rb, hasnt been released 2013 (0.6.0),   since then, there have been a number of commits to master, specifically one which fixes a whitespace issue in the path.   Can you please release version 0.6.1 of this package?

Thank you!
   Shyam

**Comment by 0xMAYANK** [comment]
We badly need this update.
Please release `v0.6.1` asap.

**Comment by killua99** [comment]
And update tag will help building process

**Comment by tmm1** [comment]
Is anyone interested in taking over maintenance of this project?

**Comment by ashie** [comment]
I've released 0.6.1 with the current code.
I skip releasing 0.6.1 for JRuby because it's currently broken.
I'll try to fix, but might not release it anymore.

**Comment by ashie** [comment]
I've yanked v0.6.1 due to lack of JRuby version #72
I'll release it as v0.7.0 (without JRuby for a while).
